### ISSUE TITLE
airtable_1.default is not a constructor

### ISSUE THREAD

**Issue by lookfirst** [Airtable/airtable.js#129]
```
TypeError: airtable_1.default is not a constructor
    at airTable (/tmp/542f6df8/src/helper.ts:10:9)
    at Object.allYour (/tmp/542f6df8/src/helper.ts:13:9)
    at default_1 (/tmp/542f6df8/api/user/login/index.ts:17:18)
```

Something changed and now it is causing this error.

helper.ts:

```
const BASE = process.env.AIRTABLE_BASE || '';
const apiKey = process.env.AIRTABLE_API_KEY;

export function airTable() {
	return new Airtable({apiKey: apiKey});
}
export function allYour() {
	return airTable().base(BASE);
}
```

login.ts:

```
export default async function(req: NowRequest, res: NowResponse) {
    const base = allYour();
    const userTable = base(C.USER_TABLE_NAME);
```

**Comment by lookfirst** [comment]
Not your fault. Something in the zeit/node builder changed. Adding this to tsconfig.json fixes it:

`    "esModuleInterop": true,`

**Comment by pookdeveloper** [comment]
Doesn't work in NestJS
