### ISSUE TITLE
AbortController: Request is not defined

### ISSUE THREAD

**Issue by reelmatt** [Airtable/airtable.js#205]
I'm running into a similar issue to #204 with the new AbortController module introduced in v0.9.0.

My Node.js/Express app still seems fine when I hit API endpoints manually, or testing through Postman. However, when trying to run unit tests with Jest (v26.3.0), it complains throwing a `ReferenceError`:

```
 FAIL  test/base.test.js
  ● Test suite failed to run

    ReferenceError: Request is not defined

      19 | 
      20 | /* SETUP */
    > 21 | const Airtable = require('airtable');
         |                  ^
      22 | 
      23 | 
      24 | 

      at Object.<anonymous> (node_modules/airtable/lib/abort-controller.js:5:25)
      at Object.<anonymous> (node_modules/airtable/lib/base.js:8:23)
      at Object.<anonymous> (node_modules/airtable/lib/airtable.js:3:12)
      at Object.<anonymous> (lib/base.js:21:18)
      at Object.<anonymous> (test/base.test.js:3:14)

```

This seems to be [expected behavior for Jest](https://github.com/facebook/jest/issues/7007#issuecomment-423137366) as they don't polyfill environments, but I'm not sure how to proceed.

Forking the repo and changing the `lib/abort-controller.js` file to the following:

```javascript
var fetch = require('node-fetch');

// istanbul ignore file
if (typeof window === 'undefined') {
    module.exports = require('abort-controller');
} else {
    if ('signal' in new fetch.Request('')) {
        module.exports = window.AbortController;
    } else {
        var polyfill = require('abortcontroller-polyfill/dist/cjs-ponyfill');
        module.exports = polyfill.AbortController;
    }
}
```

silences the `ReferenceError` when running the tests, but then throws a `TypeError: fetch is not a function.`, presumably from my poorly-hacked "solution".

Does any one have ideas on how to proceed?

**Comment by reelmatt** [comment]
@jugglinmike answered this in [#204](https://github.com/Airtable/airtable.js/issues/204#issuecomment-671551480). The solution was adding `whatwg-fetch` to the Jest setup files.
