### ISSUE TITLE
Error loading into AWS node lambda function

### ISSUE THREAD

**Issue by jonfrank** [Airtable/airtable.js#254]
I'm trying to use airtable.js in an AWS lambda function. Node 12.x or 14.x, same result. Tested locally (node 14.15.0) and working fine. Deploying the same test code to AWS lambda, whether in a lambda layer or a zipped deployment package, results in this error:
```
{
  "errorType": "Runtime.ImportModuleError",
  "errorMessage": "Error: Cannot find module '/var/task/node_modules/abort-controller/dist/abort-controller'. Please verify that the package.json has a valid \"main\" entry",
  "trace": [
    "Runtime.ImportModuleError: Error: Cannot find module '/var/task/node_modules/abort-controller/dist/abort-controller'. Please verify that the package.json has a valid \"main\" entry",
    "    at _loadUserApp (/var/runtime/UserFunction.js:100:13)",
    "    at Object.module.exports.load (/var/runtime/UserFunction.js:140:17)",
    "    at Object.<anonymous> (/var/runtime/index.js:43:30)",
    "    at Module._compile (internal/modules/cjs/loader.js:1063:30)",
    "    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)",
    "    at Module.load (internal/modules/cjs/loader.js:928:32)",
    "    at Function.Module._load (internal/modules/cjs/loader.js:769:14)",
    "    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)",
    "    at internal/main/run_main_module.js:17:47"
  ]
}
```

This looks a bit similar to issue #204 but I'm on ^0.10.1 which was meant to fix that issue.

**Comment by jonfrank** [comment]
Turns out the issue was a problem with the zip of the layer deployment package which was built into my terraform deployment. Zipping manually instead solves the problem. No idea why - need to get to the bottom of that. It's exactly what I've been doing in a different project for >20 lambdas and >5 layers with no problem at all.
