### ISSUE TITLE
Cannot read property 'offset' of undefined on `.all` call

### ISSUE THREAD

**Issue by vvscode** [Airtable/airtable.js#285]
```
(node:21610) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'offset' of undefined
    at /Users/vvscode/repo/airtableExport/node_modules/airtable/src/query.ts:162:28
    at /Users/vvscode/repo/airtableExport/node_modules/airtable/src/run_action.ts:90:25
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
```

the error happens at line 118
 of `lib/query.js` (in `node_modules/airtable`)

```js 
    var inner = function () {
        _this._table._base.runAction('get', path, params, null, function (err, response, result) {
            if (err) {
                done(err, null);
            }
            else {
                 // I put debug dump here 
                 // console.log({result, response})
                var next = void 0;
                if (result.offset) {
                    params.offset = result.offset;
                    next = inner;
                }
                else {
                    next = function () {
                        done(null);
                    };
                }
                var records = records.map(function (recordJson) {
                    return new record_1.default(_this._table, null, recordJson);
                });
                pageCallback(records, next);
            }
        });
    };
```

dumping values there gives 

```
{
  result: {
    records: [
      [Object], [Object], [Object], [Object], [Object], [Object],
      [Object], [Object], [Object], [Object], [Object], [Object],
      [Object], [Object], [Object], [Object], [Object], [Object],
      [Object], [Object], [Object], [Object], [Object], [Object],
      [Object], [Object], [Object], [Object], [Object], [Object],
      [Object], [Object], [Object], [Object], [Object], [Object],
      [Object], [Object], [Object], [Object], [Object], [Object],
      [Object], [Object], [Object], [Object], [Object], [Object],
      [Object], [Object], [Object], [Object], [Object], [Object],
      [Object], [Object], [Object], [Object], [Object], [Object],
      [Object], [Object], [Object], [Object], [Object], [Object],
      [Object], [Object], [Object], [Object], [Object], [Object],
      [Object], [Object], [Object], [Object], [Object], [Object],
      [Object], [Object], [Object], [Object], [Object], [Object],
      [Object], [Object], [Object], [Object], [Object], [Object],
      [Object], [Object], [Object], [Object], [Object], [Object],
      [Object], [Object], [Object], [Object]
    ],
    offset: 'xxxxxx/rec2qQfEbN1QLehDx'
  },
  response: {
    size: 0,
    timeout: 0,
    body: { records: [Array], offset: 'xxxxxx/rec2qQfEbN1QLehDx' },
    statusCode: 200
  }
}
{ result: undefined, response: undefined }
```

**Comment by Nazaire** [comment]
I'm also seeing this.

**Comment by ryancwalsh** [comment]
Today is my first day trying to use the Airtable API, and immediately I'm running into this issue.

I think this (285) is potentially a duplicate of https://github.com/Airtable/airtable.js/issues/246 so I'll look there.
