### ISSUE TITLE
Bug, Error: Expected signal to be an instanceof AbortSignal

### ISSUE THREAD

**Issue by bernatfortet** [Airtable/airtable.js#386]
I'm getting an error `Expected signal to be an instanceof AbortSignal` when doing any call, e.g. `select`
I assume, the same issue as https://github.com/Airtable/airtable.js/issues/205, https://github.com/Airtable/airtable.js/issues/204

I'm using next.js "next": "^13.5.2",
and using Airtable v0.12.2

After digging around I realized it's a node-fetch issues. I ended having to fork the library and edit many parts of it to make it work. Now I"m using my own version. Upgraded node-fetch and it was solved.

I think the issue is here. When doing `next dev` I'm not getting the issue, but when I'm serving or it's pushed to vercel I'm getting the issue. I think it's because it's not reaching the polyfill or something like that. 

What would be the most helpful way to support the team in fixing this issue?
```
// istanbul ignore file
let AbortController: new () => AbortController;
const browserGlobal =
    typeof window !== 'undefined' ? window : typeof self !== 'undefined' ? self : null; // self is the global in web workers
if (!browserGlobal) {
    AbortController = require('abort-controller');
} else if ('signal' in new Request('https://airtable.com')) {
    AbortController = browserGlobal.AbortController;
} else {
    const polyfill = require('abortcontroller-polyfill/dist/cjs-ponyfill');
    AbortController = polyfill.AbortController;
}

export default AbortController;
```

**Comment by bernatfortet** [comment]
@bendaly818 did you have the same issue?

**Comment by vinayman** [comment]
I have the same issue @bernatfortet

**Comment by vinayman** [comment]
@bernatfortet - Could you commit your changes to a PR? So we can hopefully expedite this change getting merged and a new Airtable.js release being tagged?

**Comment by bernatfortet** [comment]
Done: https://github.com/Airtable/airtable.js/pull/388

**Comment by Khaan25** [comment]
I'm also facing this issue, I hope it's resolved.

**Comment by Khaan25** [comment]
@bernatfortet Do you have any current workaround for it?

**Comment by Khaan25** [comment]
Hey @bernatfortet I've fixed it. It's a workaround for now but here's the code you need to add:

`{
  "dependencies": {
    "airtable": "^0.12.2",
    "next": "13.5.2",
    "node-fetch": "^3.3.2",
  },
  "overrides": {
    "airtable": {
      "node-fetch": "^3.3.1"
    }
  },
  "devDependencies": {
    "@types/airtable": "^0.10.1"
  }
}`

**Comment by bosung90** [comment]
I was getting the same error when using next14 during build
I fixed by adding following to next.conig.js

```
experimental: {
    serverMinification: false,
  },
```

**Comment by bernatfortet** [comment]
@bosung90 I assume that by doing `serverMinification: false` we're preventing next.js from being compressed. That doesn't sound ideal. I wonder if there's any other way to go around it.

**Comment by enisze** [comment]
Hey I got the same issue here, sorry to ask, but hows the progress going? 👀

**Comment by clawrence121** [comment]
Same issue here when using Airtable in NextJS 14
```
Error fetching records
TypeError: Expected signal to be an instanceof AbortSignal
    at new $ (/Users/chrislawrence/Kiwiburn/code/web-portal/.next/server/chunks/251.js:5:47196)
    at /Users/chrislawrence/Kiwiburn/code/web-portal/.next/server/chunks/251.js:5:48642
    at new Promise (<anonymous>)
    at Object.Z [as default] (/Users/chrislawrence/Kiwiburn/code/web-portal/.next/server/chunks/251.js:5:48594)
    at Object.p [as default] (/Users/chrislawrence/Kiwiburn/code/web-portal/.next/server/chunks/251.js:1:21794)
    at p.runAction (/Users/chrislawrence/Kiwiburn/code/web-portal/.next/server/chunks/251.js:1:10709)
    at w (/Users/chrislawrence/Kiwiburn/code/web-portal/.next/server/chunks/251.js:1:16808)
    at p.h (/Users/chrislawrence/Kiwiburn/code/web-portal/.next/server/chunks/251.js:1:17005)
    at p.eachPage (/Users/chrislawrence/Kiwiburn/code/web-portal/.next/server/chunks/251.js:1:12833)
    at p.v (/Users/chrislawrence/Kiwiburn/code/web-portal/.next/server/chunks/251.js:1:16089)
 ⨯ Error fetching records
```

When attempting to set to node-fetch ^3.3.2 I get this error at build:
```
Failed to compile.

./node_modules/airtable/lib/fetch.js
Module not found: ESM packages (node-fetch) need to be imported. Use 'import' to reference the package instead. https://nextjs.org/docs/messages/import-esm-externals

https://nextjs.org/docs/messages/module-not-found

Import trace for requested module:
./node_modules/airtable/lib/base.js
./node_modules/airtable/lib/airtable.js
./src/api-services/airtable-helper.ts
./src/api-services/burnerProfile.ts
./src/app/(auth)/tickets/purchase/allocate/actions.ts
./node_modules/next/dist/build/webpack/loaders/next-flight-action-entry-loader.js?actions=%5B%5B%22%2FUsers%2Fchrislawrence%2FKiwiburn%2Fcode%2Fweb-portal%2Fsrc%2Fapp%2F(auth)%2Ftickets%2Fpurchase%2Fallocate%2Factions.ts%22%2C%5B%22%24%24ACTION_1%22%2C%22removeTicketOfferFromBurnerProfile%22%2C%22assignTicketOfferToBurnerProfile%22%2C%22%24%24ACTION_0%22%5D%5D%2C%5B%22%2FUsers%2Fchrislawrence%2FKiwiburn%2Fcode%2Fweb-portal%2Fsrc%2Fapi-services%2Fstripe.ts%22%2C%5B%22redirectToCheckoutSession%22%2C%22getCheckoutSession%22%5D%5D%5D&__client_imported__=true!

./node_modules/airtable/lib/fetch.js
Module not found: ESM packages (node-fetch) need to be imported. Use 'import' to reference the package instead. https://nextjs.org/docs/messages/import-esm-externals

https://nextjs.org/docs/messages/module-not-found

Import trace for requested module:
./node_modules/airtable/lib/base.js
./node_modules/airtable/lib/airtable.js
./src/api-services/airtable-helper.ts
./src/api-services/burnerProfile.ts
./src/app/(guest)/auth/login/callback/route.ts


> Build failed because of webpack errors

**Comment by clawrence121** [comment]
I was able to get it working for Next 14 with the App Router with the following:
- Next 14.1.3
- Node 18.17.1
- Airtable 0.12.2

Working with App Router, Server Actions and Route Handlers, both locally with next start and on vercel.

```
// package.json
{
  "engines": {
    "node": ">=18.17.0 <19.0.0"
  },
  "dependencies": {
    "airtable": "^0.12.2",
    "next": "14.1.3",
    "node-fetch": "^3.3.2",
  },
  "devDependencies": {
    "@types/airtable": "^0.10.1",
  },
  "overrides": {
    "airtable": {
      "abortcontroller-polyfill": "^1.7.5",
      "node-fetch": "^3.3.2"
    }
  }
}
```

```
// next.config.js
/** @type {import('next').NextConfig} */
const nextConfig = {
  experimental: {
    esmExternals: 'loose',
  },
};

module.exports = nextConfig;
```

**Comment by enisze** [comment]
> I was able to get it working for Next 14 with the App Router with the following:
> 
> * Next 14.1.3
> * Node 18.17.1
> * Airtable 0.12.2
> 
> Working with App Router, Server Actions and Route Handlers, both locally with next start and on vercel.
> 
> ```
> // package.json
> {
>   "engines": {
>     "node": ">=18.17.0 <19.0.0"
>   },
>   "dependencies": {
>     "airtable": "^0.12.2",
>     "next": "14.1.3",
>     "node-fetch": "^3.3.2",
>   },
>   "devDependencies": {
>     "@types/airtable": "^0.10.1",
>   },
>   "overrides": {
>     "airtable": {
>       "abortcontroller-polyfill": "^1.7.5",
>       "node-fetch": "^3.3.2"
>     }
>   }
> }
> ```
> 
> ```
> // next.config.js
> /** @type {import('next').NextConfig} */
> const nextConfig = {
>   experimental: {
>     esmExternals: 'loose',
>   },
> };
> 
> module.exports = nextConfig;
> ```
> 
> Just doing the node-fetch override from above didn't work, I had to add the abortcontroller-polyfill override as well.

This did not work for me @clawrence121 still getting the same error.

It works with this:
```    serverMinification: false ``` 
Although I don't think we should use this.

**Comment by evanfurniss** [comment]
Commenting for exposure, same issue with AbortController

- next: 14.0.4
- node: 20.9.0
- airtable: 0.12.2

**Comment by wouterds** [comment]
We're using Airtable in our Node.js API (bundled with esbuild, running in Docker Node 22 alpine) and are seeing this issue as well. Supposedly because the package is minified by esbuild. Turning it off could fix it but that's not something we want. So instead we're excluding the airtable package with esbuild externals and are installing it manually in the Docker build, which is a horrendous workaround.

Would be goud if this package gets some love, looks like it hasn't received any meaningful maintenance or updates in the last 5 years from going through the source.

**Comment by tschirky** [comment]
We're experiencing the same issue as well (node 22, esbuild).

According to Airtable, this is the official API client (https://airtable.com/developers/web/api/introduction).
But years of open issues doesn't seem to me like official API client...
