### ISSUE TITLE
Official Airtable JS Client does not work on App Engine Standard environment (TypeError: Expected signal to be an instanceof AbortSignal)

### ISSUE THREAD

**Issue by mrbaguettefr** [Airtable/airtable.js#400]
Tested with
- airtable 0.12.2
- App Engine Node runtime 18 and 20

Project works perfectly locally.

Stacktrace :
"    at e.c (/workspace/.next/server/chunks/59.js:1:16231)"
"    at e.eachPage (/workspace/.next/server/chunks/59.js:1:12890)"
"    at e.h (/workspace/.next/server/chunks/59.js:1:17147)"
"    at w (/workspace/.next/server/chunks/59.js:1:16950)"
"    at e.runAction (/workspace/.next/server/chunks/59.js:1:10754)"
"    at Object.e [as default] (/workspace/.next/server/chunks/59.js:1:21963)"
"    at Object.G [as default] (/workspace/.next/server/chunks/59.js:30:127610)"
"    at new Promise (<anonymous>)"
"    at /workspace/.next/server/chunks/59.js:30:127658"
"    at new z (/workspace/.next/server/chunks/59.js:30:126212)"
" ⨯ TypeError: Expected signal to be an instanceof AbortSignal"

**Comment by totobest** [comment]
Related to https://github.com/Airtable/airtable.js/issues/386

**Comment by evanfurniss** [comment]
Seconded that this is broken. Rolled back Next.js to an older version worked, so did using experimental feature to stop server minification, but that's a bad idea.

Awaiting response from Airtable.
